//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About</summary>
	[PublishedModel("about")]
	public partial class About : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "about";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<About, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public About(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// AboutUsText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsText")]
		public virtual string AboutUsText => this.Value<string>(_publishedValueFallback, "aboutUsText");

		///<summary>
		/// AboutUsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutUsTitle")]
		public virtual string AboutUsTitle => this.Value<string>(_publishedValueFallback, "aboutUsTitle");

		///<summary>
		/// ContactInformationAddress
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationAddress")]
		public virtual string ContactInformationAddress => this.Value<string>(_publishedValueFallback, "contactInformationAddress");

		///<summary>
		/// ContactInformationEmail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationEmail")]
		public virtual string ContactInformationEmail => this.Value<string>(_publishedValueFallback, "contactInformationEmail");

		///<summary>
		/// ContactInformationEmailAddress
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationEmailAddress")]
		public virtual string ContactInformationEmailAddress => this.Value<string>(_publishedValueFallback, "contactInformationEmailAddress");

		///<summary>
		/// ContactInformationLocation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationLocation")]
		public virtual string ContactInformationLocation => this.Value<string>(_publishedValueFallback, "contactInformationLocation");

		///<summary>
		/// ContactInformationPhone
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationPhone")]
		public virtual string ContactInformationPhone => this.Value<string>(_publishedValueFallback, "contactInformationPhone");

		///<summary>
		/// ContactInformationPhoneNumber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationPhoneNumber")]
		public virtual string ContactInformationPhoneNumber => this.Value<string>(_publishedValueFallback, "contactInformationPhoneNumber");

		///<summary>
		/// ContactInformationPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactInformationPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactInformationPicture");

		///<summary>
		/// ContactInformationTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactInformationTitle")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ContactInformationTitle => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "contactInformationTitle");

		///<summary>
		/// FooterPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops FooterPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "footerPicture");

		///<summary>
		/// HeaderLogo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeaderLogo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "headerLogo");

		///<summary>
		/// OurExpertBoxBoxFivePicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxBoxFivePicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertBoxBoxFivePicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertBoxBoxFivePicture");

		///<summary>
		/// OurExpertBoxFiveText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxFiveText")]
		public virtual string OurExpertBoxFiveText => this.Value<string>(_publishedValueFallback, "ourExpertBoxFiveText");

		///<summary>
		/// OurExpertBoxFiveTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxFiveTitle")]
		public virtual string OurExpertBoxFiveTitle => this.Value<string>(_publishedValueFallback, "ourExpertBoxFiveTitle");

		///<summary>
		/// OurExpertBoxFourPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxFourPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertBoxFourPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertBoxFourPicture");

		///<summary>
		/// OurExpertBoxFourText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxFourText")]
		public virtual string OurExpertBoxFourText => this.Value<string>(_publishedValueFallback, "ourExpertBoxFourText");

		///<summary>
		/// OurExpertBoxFourTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxFourTitle")]
		public virtual string OurExpertBoxFourTitle => this.Value<string>(_publishedValueFallback, "ourExpertBoxFourTitle");

		///<summary>
		/// OurExpertBoxOnePicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxOnePicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertBoxOnePicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertBoxOnePicture");

		///<summary>
		/// OurExpertBoxOneText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxOneText")]
		public virtual string OurExpertBoxOneText => this.Value<string>(_publishedValueFallback, "ourExpertBoxOneText");

		///<summary>
		/// OurExpertBoxOneTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxOneTitle")]
		public virtual string OurExpertBoxOneTitle => this.Value<string>(_publishedValueFallback, "ourExpertBoxOneTitle");

		///<summary>
		/// OurExpertBoxSevenPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxSevenPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertBoxSevenPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertBoxSevenPicture");

		///<summary>
		/// OurExpertBoxSevenText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxSevenText")]
		public virtual string OurExpertBoxSevenText => this.Value<string>(_publishedValueFallback, "ourExpertBoxSevenText");

		///<summary>
		/// OurExpertBoxSevenTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxSevenTitle")]
		public virtual string OurExpertBoxSevenTitle => this.Value<string>(_publishedValueFallback, "ourExpertBoxSevenTitle");

		///<summary>
		/// OurExpertBoxSixPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxSixPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertBoxSixPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertBoxSixPicture");

		///<summary>
		/// OurExpertBoxSixText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxSixText")]
		public virtual string OurExpertBoxSixText => this.Value<string>(_publishedValueFallback, "ourExpertBoxSixText");

		///<summary>
		/// OurExpertBoxSixTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxSixTitle")]
		public virtual string OurExpertBoxSixTitle => this.Value<string>(_publishedValueFallback, "ourExpertBoxSixTitle");

		///<summary>
		/// OurExpertBoxThreePicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxThreePicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertBoxThreePicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertBoxThreePicture");

		///<summary>
		/// OurExpertBoxThreeText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxThreeText")]
		public virtual string OurExpertBoxThreeText => this.Value<string>(_publishedValueFallback, "ourExpertBoxThreeText");

		///<summary>
		/// OurExpertBoxThreeTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxThreeTitle")]
		public virtual string OurExpertBoxThreeTitle => this.Value<string>(_publishedValueFallback, "ourExpertBoxThreeTitle");

		///<summary>
		/// OurExpertBoxTwoPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxTwoPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertBoxTwoPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertBoxTwoPicture");

		///<summary>
		/// OurExpertBoxTwoText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxTwoText")]
		public virtual string OurExpertBoxTwoText => this.Value<string>(_publishedValueFallback, "ourExpertBoxTwoText");

		///<summary>
		/// OurExpertBoxTwoTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertBoxTwoTitle")]
		public virtual string OurExpertBoxTwoTitle => this.Value<string>(_publishedValueFallback, "ourExpertBoxTwoTitle");

		///<summary>
		/// OurExpertText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString OurExpertText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "ourExpertText");

		///<summary>
		/// OurExpertTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertTitle")]
		public virtual string OurExpertTitle => this.Value<string>(_publishedValueFallback, "ourExpertTitle");

		///<summary>
		/// ReviewsMainText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsMainText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ReviewsMainText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "reviewsMainText");

		///<summary>
		/// ReviewsPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReviewsPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "reviewsPicture");

		///<summary>
		/// ReviewsText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ReviewsText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "reviewsText");

		///<summary>
		/// ReviewsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsTitle")]
		public virtual string ReviewsTitle => this.Value<string>(_publishedValueFallback, "reviewsTitle");

		///<summary>
		/// TinaFoxMainText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tinaFoxMainText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString TinaFoxMainText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "tinaFoxMainText");

		///<summary>
		/// TinaFoxPicture
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tinaFoxPicture")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TinaFoxPicture => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "tinaFoxPicture");

		///<summary>
		/// TinaFoxText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tinaFoxText")]
		public virtual string TinaFoxText => this.Value<string>(_publishedValueFallback, "tinaFoxText");

		///<summary>
		/// TinaFoxTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tinaFoxTitle")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString TinaFoxTitle => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "tinaFoxTitle");
	}
}
